server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zhang51260
    url: jdbc:mysql://192.168.3.114:3306/myBusiness?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    #控制台日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml

ftp:
  ip: 192.168.3.114
  port: 21
  prefix: http://img.zjh.pub/
  user: ftpuser
  pass: 123456

alipay:
  callback_url: http://zjh-mall.natapp1.cc/order/alipay_callback.do
